### ISSUE TITLE
Issues with running on Mac

### ISSUE THREAD

**Issue by mykeels** [simple-lang/simple#62]
# Description

I successfully built simple for Mac, but it's refusing to compile the example *.sim code.

## Expected behavior

I expect that `simple ../examples/algorithms/degreeToRadian.sim` would actually run the `degreeToRadian.sim` file.

## Actual behavior

It does not

![image](https://user-images.githubusercontent.com/11996508/54112684-014f6e80-43e7-11e9-9bc6-1a97ecc35d1e.png)

**Comment by Thecarisma** [comment]
`systemic` and `string_savant` are dynamic modules which provide low level access. The reason for this error is because the dynamic modules has not been built. 
In the source `../examples/algorithms/degreeToRadian.sim` the call to `simple.util.Math` requires some dynamic module to be available. 

This is currently the number 1 priority, build scripts has been written for MacOSX and complete build on MAC has been achieved and will be made available to the public in an archive format before March 12 .

**Comment by mykeels** [comment]
So, how can I build the dynamic libraries?

**Comment by Thecarisma** [comment]
Very well I ll commit to master soon

**Comment by Thecarisma** [comment]
You can pull from master and use the /build/Mac-Build.sh script to build completely from source

**Comment by Thecarisma** [comment]
I think this issue can be closed
